// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         {children}
//       </body>
//     </html>
//   );
// }



// app/layout.tsx
import './globals.css'
import type { ReactNode } from 'react'
import Link from 'next/link'

export const metadata = { title: 'My Training — Home', description: 'Training & Courses' }

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body className="min-h-screen flex flex-col">
        <header className="bg-white shadow">
          <div className="container mx-auto px-6 py-4 flex items-center justify-between">
            <Link href="/" className="text-xl font-semibold">My Training</Link>
            <nav className="space-x-4">
              <Link href="/" className="hover:underline">Home</Link>
              <Link href="/about" className="hover:underline">About</Link>
              <Link href="/courses" className="hover:underline">Courses</Link>
              <Link href="/contact" className="hover:underline">Contact</Link>
            </nav>
          </div>
        </header>

        <main className="container mx-auto px-6 py-10 flex-1">{children}</main>

        <footer className="bg-gray-100">
          <div className="container mx-auto px-6 py-6 text-center text-sm text-gray-600">
            © {new Date().getFullYear()} My Training. All rights reserved.
          </div>
        </footer>
      </body>
    </html>
  )
}
